Задача идемпотентности (этап 3):
При попытке проверять строку перед вставкой в staging.user_order_log в Airflow-логе вижу ошибку:

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) constraint "user_order_log_pk" for table "staging.user_order_log" does not exist

При этом ограничение существует (проверяла через dbeaver). Почему так может быть?


Функция для проверки дубликатов и игнорирования таких строк лежит в utils.py
Также в этой функции пробовала передавать не название constraint, а index_elements=['uniq_id'], результат такой же.

В даге ее вызываю так:
row_count = df.to_sql(f"{pg_schema}.{pg_table}", engine, if_exists='append', index=False, method=insert_on_duplicate)

Сейчас закомментировала эту строку и оставила стандартный вариант (не получилось устранить ошибку выше).